source 'https://rubygems.org'

# Base gems

gem 'rails', '~> 4.2.0'
gem 'sqlite3'

gem 'jquery-rails'
gem 'jbuilder', '~> 1.2'

gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'

gem 'thin', group: [:development]
# gem 'therubyracer', platforms: :ruby

# delayed jobs
gem 'redis'
gem 'sidekiq'

# App gems
gem 'haml'
gem 'sorcery'
gem 'kaminari'
gem 'haml-rails'
gem 'rails_config'

gem 'pry-rails'

gem 'the_data_role_block_jquery',
  path: '../../../the_data_role_block_jquery'

gem 'the_data_role_block_haml_41',
  path: '../../../the_data_role_block_haml_41'

# gem 'the_data_role_block_haml_40',
#   path: '../../../the_data_role_block_haml_40'

# The Log
gem 'the_log'
  # path: '../../../the_log'

# TheComments requires
gem 'the_comments',
  path: '../../'

gem 'the_notification',
  github: 'TheProfitCMS/the_notification',
  branch: 'master'

gem 'bootstrap-sass',
  github: 'thomas-mcdonald/bootstrap-sass'

gem 'awesome_nested_set',
  git: 'https://github.com/collectiveidea/awesome_nested_set.git',
  branch: 'master'

# Test gems
group :development, :test do
  gem 'faker'
  gem 'timecop'
  gem 'factory_girl'
  gem "factory_girl_rails"
  gem 'rspec-rails', '~> 2.0'

  # gem 'database_cleaner'
end
