source 'https://rubygems.org'

# Base gems
gem 'rails', '4.0.0'
gem 'sqlite3'

gem 'jquery-rails'
gem 'jbuilder', '~> 1.2'

gem 'uglifier', '>= 1.3.0'
gem 'sass-rails', '~> 4.0.0'
gem 'coffee-rails', '~> 4.0.0'

gem 'thin', group: [:development]
gem 'therubyracer', platforms: :ruby
gem 'sdoc', require: false, group: [:doc]

# App gems
gem 'haml'
gem 'sorcery'
gem 'haml-rails'
gem 'awesome_nested_set'
gem 'the_comments', path: '../../'

# Test gems
group :development, :test do
  gem 'faker'
  gem 'factory_girl'
  gem 'database_cleaner'
  gem 'rspec-rails', '~> 2.0'
end